import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Header } from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={cn(
          "min-h-screen font-sans antialiased",
          geistSans.variable,
          geistMono.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <HomeLayout>{children}</HomeLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}

function HomeLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="relative flex flex-col min-h-screen ">
      <header className="sticky top-0 z-50 w-full border-b backdrop-blur">
        <Header />
      </header>
      <main className="flex-1">
        <div className="w-full h-full">{children}</div>
      </main>
      <footer className="border-t">
        <Footer />
      </footer>
    </div>
  );
}
